[project]
name = "polars-readstat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "maturin>=1.8.3",
    "polars>=1.27.1",
]
